[package]
name = "kube_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.84" }
k8s-openapi = { version = "0.18", features = ["v1_26"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
