version: '3.8'

services:
  localai:
    extends:
      file: docker-compose.yml
      service: localai
    environment:
      - LOCALAI_DEBUG=true
      - TEST_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  k8sgpt:
    extends:
      file: docker-compose.yml
      service: k8sgpt
    environment:
      - K8SGPT_TEST_MODE=true
      - K8SGPT_LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "k8sgpt version"]
      interval: 10s
      timeout: 5s
      retries: 3

  kube-app:
    extends:
      file: docker-compose.yml
      service: kube-app
    environment:
      - RUST_LOG=debug
      - TEST_ENV=true
      - MOCK_K8S_API=true
    depends_on:
      localai:
        condition: service_healthy
      k8sgpt:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/health_check"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  test-models:
    driver: local
  test-output:
    driver: local

networks:
  test-network:
    driver: bridge

