certificateEnabled: true

service:
  port: 8080
  type: ClusterIP

gateway:
  enabled: true

localai:
  enabled: true
  env:
    CONTEXT_SIZE: "0"
    THREADS: "4"
  persistence:
    models:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClassName: microk8s-hostpath
    output:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClassName: microk8s-hostpath

fullnameOverride: localai
