apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: localai
spec:
  secretName: test-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: test.local
  dnsNames:
  - test.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

