# Override name of generated resources
fullnameOverride: "nginx-server"

# Number of replicas
replicaCount: 1

# Image configuration
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80

# Gateway API configuration
gateway:
  enabled: true
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
      tls: {}
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: example-cert-tls
            kind: Secret
            group: ""

# HTTPRoute configuration
routes:
  - enabled: true
    hostnames:
      - "example.local"
    rules:
      - backendRefs:
          - name: nginx-server
            port: 80
    redirectHTTPtoHTTPS: true
