{{- if .Values.gateway.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.fullnameOverride }}-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.gateway.hostname }}
  dnsNames:
    - {{ .Values.gateway.hostname }}
{{- end }}
