apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: kube-example
          image: nginx:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: example-cert-tls
