{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        certificateRefs:
        - kind: Secret
          name: {{ .Values.fullnameOverride }}-tls
        mode: Terminate
    {{- end }}
{{- end }}
