{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "helm-chart.fullname" . }}
    kind: Gateway
    group: gateway.networking.k8s.io
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ .host | quote }}
  {{- end }}
  rules:
  {{- range .Values.gateway.hosts }}
  {{- range .paths }}
  - matches:
    - path:
        type: {{ .pathType }}
        value: {{ .path }}
    backendRefs:
    - name: {{ include "helm-chart.fullname" $ }}
      kind: Service
      group: ""
      port: {{ $.Values.service.port }}
  {{- end }}
  {{- end }}
{{- end }}
