{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.fullnameOverride }}
    kind: Gateway
    group: gateway.networking.k8s.io
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - name: {{ .Values.fullnameOverride }}-{{ .Values.fullnameOverride }}
        kind: Service
        port: {{ .Values.localai.service.port }}
{{- end }}
