apiVersion: core.k8sgpt.ai/v1
kind: K8sGPT
metadata:
  name: {{ .Release.Name }}-k8sgpt
  namespace: {{ .Release.Namespace }}
spec:
  backend:
    type: localai
    baseUrl: http://{{ .Release.Name }}-localai:8080
    model: {{ .Values.k8sgpt.model }}
  noCache: true
  version: {{ .Values.k8sgpt.version }}
  analyze:
    enabled: true
  filter:
    enabled: false
  generate:
    enabled: true
  sink:
    enabled: false
  analytics:
    enabled: false

apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: {{ .Values.k8sgpt.name | default "k8sgpt-default" }}
  namespace: {{ .Release.Namespace }}
spec:
  backend: {{ .Values.k8sgpt.backend | default "localai" }}
  model: {{ .Values.k8sgpt.model | default "gpt-4" }}
  analytics:
    enabled: {{ .Values.k8sgpt.analytics.enabled | default false }}

