{{- if and .Values.localai.enabled .Values.localai.persistence.models.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "localai.fullname" . }}-models
  labels:
    {{- include "localai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
{{- end }}
