{{- if .Values.localai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "localai.fullname" . }}
  labels:
    {{- include "localai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.localai.service.type }}
  ports:
    - port: {{ .Values.localai.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "localai.selectorLabels" . | nindent 4 }}
{{- end }}

