apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app: example
