apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localai-storage-wait
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
